name: Docker Image CI

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        
      - name: Docker Registry Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          
      - name: Docker Build and Push
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
          
          
